spring:
  application:
    name: gateway-service

server:
  port: 8080
 
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
 
zuul:
  # allows defining an application to route certain requests, based on an ant URL matcher
  routes:
    # route any request that comes in on ‘/product-service/**’ to an application with the spring.application.name of ‘product-service’
    # Zuul will lookup the service from discovery server (using the application name) and will forward the request to that service
    product-service:
      path: /product-service/**
      sensitive-headers: Set-Cookie,Authorization

    order-service:
      path: /rating-service/**
      sensitive-headers: Set-Cookie,Authorization

    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082

hystrix:
  command:
    product-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
 
    order-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

# logging settings
logging:
  level:
    root: info
    com:
      netflix: error
    org:
      apache: warn
      springframework: warn

  pattern:
    # special characters need to be escaped / quoted
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%thread) %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'